server:
  forward-headers-strategy: framework
  port: 8080
  undertow:
    no-request-timeout: 60000
    accesslog:
      enabled: true
      dir: logs/access_log/
      pattern: '%{i,X-Forwarded-For} %h %l %u %t %r %s %b "%{i,Referer}" "%{i,User-Agent}" %T'
      rotate: true
      prefix: access_log.
      suffix: log

spring:
  pid:
    fail-on-write-error: true
    file: pid/app.pid
  devtools:
    livereload:
      enabled: true

management:
  server:
    port: 8081
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health, info
  health:
    ping:
      enabled: true
