server:
  error:
    include-exception: false
    include-stacktrace: never
    whitelabel:
      enabled: false
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  shutdown: graceful

spring:
  application:
    name: Spring Authorization Server Kotlin Example Application
  jackson:
    time-zone: Asia/Seoul
  lifecycle:
    timeout-per-shutdown-phase: 1m
  profiles:
    active:
      - example
      - secret-example

management:
  endpoints:
    enabled-by-default: false
    jmx:
      exposure:
        exclude: "*"
